version: '3'
services:
  node:
    container_name: "node"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/var/www/html
    tty: true
    ports:
        - "3000:3000"
        - "8080:8080"
        - "5000:5000"
        - "9005:9005"
